- hosts: localhost
  gather_facts: no
  become: no

  vars:
    image_name: "ansible-homework"
    image_tag: "0.01"
    listen_port: "5001"
    docker_username: "vodoprovod4ika"

  tasks:
    - name: Create code dir
      file:
        dest: code/
        state: directory

    - name: Get latest app code from github
      git:
        repo: https://github.com/vutoff/devops-programme
        version: main
        dest: code/

    - name: Install Python requirements
      pip:
        chdir: code/
        requirements: requirements.txt
        state: present

    - name: Build docker image
      shell: "docker build -t {{ image_name }}:{{ image_tag }} ."

    - name: Docker tag image
      shell: "docker tag {{ image_name }}:{{ image_tag }} {{ docker_username }}/{{ image_name }}:{{ image_tag }}"
    
    - name: Push docker image
      shell: "docker push {{ docker_username }}/{{ image_name }}:{{image_tag}}"

    - name: Run docker image
      shell: "docker run --name {{ image_name }} -p {{ listen_port }}:{{ listen_port }} {{ docker_username }}/{{ image_name }}:{{image_tag}}"